-----------------------------------------------
-- JFD'S RULE WITH FAITH
-----------------------------------------------

CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType  			text 		 		DEFAULT NULL,
	GovernmentType			text 	 			DEFAULT NULL,
	LeaderTitle				text				DEFAULT NULL,
	PolicyType  			text 		 		DEFAULT NULL,
	UseFeminine				BOOLEAN				DEFAULT 0,
	TitleIsFullName			BOOLEAN				DEFAULT 0);
	
INSERT INTO Civilization_Titles
		(CivilizationType, 			GovernmentType, 								PolicyType,				LeaderTitle)
VALUES	('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_BERBER'),						--Chiefdom	-- Amghar
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_BERBER'),						--Horde	-- Baba
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_BERBER'),						--Polis -- Amghiwan
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_BERBER'),					--Autocracy -- Amalway
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_BERBER'),					--Oligarchy -- Ahaggar
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_BERBER'),			--Classical Democracy -- Anesmigel
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_BERBER'),				--Feudal Monarchy -- Agellid
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_BERBER'),			--Merchant Republic -- Amastag
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_BERBER'),			--Theocracy -- Aselmad
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_BERBER'),						--Absolute Monarchy -- Agellid
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_BERBER'),						--Constitutional Monarchy -- Agellid
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_BERBER'),					--Noble Republic -- Ageldun
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_BERBER'),			--Liberal Democracy -- Aselway
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_BERBER'),				--People's Republic -- Amalway
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_BERBER'),		--Military Guardianship -- Gma Ameqran
		('CIVILIZATION_CVS_BERBER',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_BERBER'),						--Empire -- Amenkad
		
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Chiefdom	-- Tamghart
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_BERBER_FEMININE'),						--Horde	-- Yemma
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_BERBER_FEMININE'),						--Polis -- Tamghiwant
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Autocracy -- Tamalwayt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Oligarchy -- Tahaggart
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_BERBER_FEMININE'),		--Classical Democracy -- Tanesmigelt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_BERBER_FEMININE'),			--Feudal Monarchy -- Tagellidt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_BERBER_FEMININE'),			--Merchant Republic -- Tamastagt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_BERBER_FEMININE'),		--Theocracy -- Taselmadt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Absolute Monarchy -- Tagellidt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Constitutional Monarchy -- Tagellidt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_BERBER_FEMININE'),					--Noble Republic -- Tageldunt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_BERBER_FEMININE'),			--Liberal Democracy -- Taselwayt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_BERBER_FEMININE'),			--People's Republic -- Tamalwayt
		('CIVILIZATION_CVS_BERBER',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_BERBER_FEMININE'),		--Military Guardianship -- Taweltmatt Tameqrant
		('CIVILIZATION_CVS_BERBER',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_BERBER_FEMININE');					--Empire -- Tamenkadt
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_BERBER' AND GovernmentType IS NOT null AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_BERBER' AND PolicyType IS NOT null AND PolicyType NOT IN (SELECT PolicyType FROM Policies);				

-- And then in case the update hasn't come out yet:

INSERT INTO Leader_Titles
				(LeaderType, 					GovernmentType, 							PolicyType,				LeaderTitle																	)
SELECT DISTINCT	'LEADER_CVS_DIHYA',		GovernmentType, 							PolicyType,				LeaderTitle
FROM Civilization_Titles WHERE LeaderTitle LIKE "%FEMININE" AND CivilizationType = 'CIVILIZATION_CVS_BERBER';

