--==========================================================================================================================
-- Berbers / City List (SeelingCat)
--==========================================================================================================================
INSERT OR REPLACE INTO LocalizedText
        (Tag,    Language,    Text)
VALUES ("LOC_CITY_NAME_SC_TLEMCEN", "en_US", "Tlemcen"),
("LOC_CITY_NAME_SC_FEZ", "en_US", "Fez"),
("LOC_CITY_NAME_SC_TOUGGOURT", "en_US", "Touggourt"),
("LOC_CITY_NAME_SC_GHARDAIA", "en_US", "Ghardaia"),
("LOC_CITY_NAME_SC_CONSTANTINE", "en_US", "Constantine"),
("LOC_CITY_NAME_SC_BEJAIA", "en_US", "Bejaia"),
("LOC_CITY_NAME_SC_TETOUAN", "en_US", "Tetouan"),
("LOC_CITY_NAME_SC_ANNABA", "en_US", "Annaba"),
("LOC_CITY_NAME_SC_BISKRA", "en_US", "Biskra"),
("LOC_CITY_NAME_SC_GERMA", "en_US", "Germa"),
("LOC_CITY_NAME_SC_CHERCHELL", "en_US", "Cherchell"),
("LOC_CITY_NAME_SC_OUARZAZATE", "en_US", "Ouarzazate"),
("LOC_CITY_NAME_SC_GHADAMES", "en_US", "Ghadames"),
("LOC_CITY_NAME_SC_SETIF", "en_US", "Setif"),
("LOC_CITY_NAME_SC_MISURATA", "en_US", "Misurata"),
("LOC_CITY_NAME_SC_SALE", "en_US", "Sale"),
("LOC_CITY_NAME_SC_TAMANRASSET", "en_US", "Tamanrasset"),
("LOC_CITY_NAME_SC_LAGHOUAT", "en_US", "Laghouat"),
("LOC_CITY_NAME_SC_AGADEZ", "en_US", "Agadez"),
("LOC_CITY_NAME_SC_ESSOUK", "en_US", "Essouk"),
("LOC_CITY_NAME_SC_AGADIR", "en_US", "Agadir"),
("LOC_CITY_NAME_SC_TINMEL", "en_US", "Tinmel"),
("LOC_CITY_NAME_SC_BATNA", "en_US", "Batna"),
("LOC_CITY_NAME_SC_TEBESSA", "en_US", "Tebessa"),
("LOC_CITY_NAME_SC_DJERBA", "en_US", "Djerba"),
("LOC_CITY_NAME_SC_KHENCHELA", "en_US", "Khenchela"),
("LOC_CITY_NAME_SC_MARRAKESH", "en_US", "Marrakesh"),
("LOC_CITY_NAME_SC_ALGIERS", "en_US", "Algiers"),
("LOC_CITY_NAME_SC_TUNIS", "en_US", "Tunis"),
-- ("LOC_CITY_NAME_TRIPOLI", "en_US", "Tripoli"), -- Already exists @ Arabia
("LOC_CITY_NAME_SC_TIZI_OUZOU", "en_US", "Tizi Ouzou"),
("LOC_CITY_NAME_SC_KAIROUAN", "en_US", "Kairouan"),
("LOC_CITY_NAME_SC_OUARGLA", "en_US", "Ouargla"),
-- ("LOC_CITY_NAME_ORAN", "en_US", "Oran"), -- Already exists @ Spain
("LOC_CITY_NAME_SC_SIJILMASA", "en_US", "Sijilmasa"),
("LOC_CITY_NAME_SC_BLIDA", "en_US", "Blida"),
("LOC_CITY_NAME_SC_AIT_BENHADDOU", "en_US", "Ait Benhaddou"),
("LOC_CITY_NAME_SC_TATAOUINE", "en_US", "Tataouine"),
("LOC_CITY_NAME_SC_ZUWARAH", "en_US", "Zuwarah"),
("LOC_CITY_NAME_SC_TENES", "en_US", "Tenes"),
("LOC_CITY_NAME_SC_MEDEA", "en_US", "Medea"),
("LOC_CITY_NAME_SC_GHAT", "en_US", "Ghat"),
("LOC_CITY_NAME_SC_TIARET", "en_US", "Tiaret"),
("LOC_CITY_NAME_SC_UBARI", "en_US", "Ubari"),
("LOC_CITY_NAME_SC_MEKNES", "en_US", "Meknes"),
("LOC_CITY_NAME_SC_TIMGAD", "en_US", "Timgad"),
("LOC_CITY_NAME_SC_GAFSA", "en_US", "Gafsa"),
("LOC_CITY_NAME_SC_LARACHE", "en_US", "Larache"),
("LOC_CITY_NAME_SC_ABALESSA", "en_US", "Abalessa"),
("LOC_CITY_NAME_SC_OUJDA", "en_US", "Oujda"),
("LOC_CITY_NAME_SC_ALTAVA", "en_US", "Altava"),
("LOC_CITY_NAME_SC_MOGADOR", "en_US", "Mogador"),
("LOC_CITY_NAME_SC_FIGUIG", "en_US", "Figuig"),
("LOC_CITY_NAME_SC_MASCARA", "en_US", "Mascara"),
("LOC_CITY_NAME_SC_DJANET", "en_US", "Djanet"),
("LOC_CITY_NAME_SC_TOZEUR", "en_US", "Tozeur"),
("LOC_CITY_NAME_SC_JIJEL", "en_US", "Jijel"),
("LOC_CITY_NAME_SC_ARAOUANE", "en_US", "Araouane"),
("LOC_CITY_NAME_SC_THAGASTE", "en_US", "Thagaste"),
("LOC_CITY_NAME_SC_TAMENTIT", "en_US", "Tamentit"),
("LOC_CITY_NAME_SC_CEUTA", "en_US", "Ceuta"),
("LOC_CITY_NAME_SC_MELILLA", "en_US", "Melilla"),
("LOC_CITY_NAME_SC_TANGIER", "en_US", "Tangier"),
("LOC_CITY_NAME_SC_CASABLANCA", "en_US", "Casablanca"),
("LOC_CITY_NAME_SC_TAGHAZA", "en_US", "Taghaza"),
("LOC_CITY_NAME_SC_AUZIA", "en_US", "Auzia"),
("LOC_CITY_NAME_SC_DOUIRET", "en_US", "Douiret"),
("LOC_CITY_NAME_SC_CHENINI", "en_US", "Chenini"),
("LOC_CITY_NAME_SC_SAFI", "en_US", "Safi"),
("LOC_CITY_NAME_SC_LAMBAESIS", "en_US", "Lambaesis"),
("LOC_CITY_NAME_SC_SIGA", "en_US", "Siga"),
("LOC_CITY_NAME_SC_THELEPTE", "en_US", "Thelepte"),
("LOC_CITY_NAME_SC_RAS_KEBDANA", "en_US", "Ras Kebdana");