--==========================================================================================================================
--
--            .
--            |\
--            | \
--            |  \
--            |   \
--            |    \          Berbers by CIVITAS
--            |     \
--            |      \
--            |       \       ____O
--            |        \     .' ./
--            |   _.,-~"\  .',/~'
--            <-~"   _.,-~" ~ |
--^"~-,._.,-~"^"~-,._\       /,._.,-~"^"~-,._.,-~"^"~-,._
--~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--==========================================================================================================================
-- Berbers / Defines
--==========================================================================================================================
-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO Types	
		(Type,							Kind)
VALUES	('CIVILIZATION_CVS_BERBER',		'KIND_CIVILIZATION');
-----------------------------------------------
-- Civilizations
-----------------------------------------------	
INSERT INTO Civilizations	
		(CivilizationType,
		Name,
		Description,
		Adjective,
		StartingCivilizationLevelType,
		RandomCityNameDepth,
		Ethnicity
		)
VALUES	(
		'CIVILIZATION_CVS_BERBER', -- CivilizationType
		'LOC_CIVILIZATION_CVS_BERBER_NAME', -- Name
		'LOC_CIVILIZATION_CVS_BERBER_DESCRIPTION', -- Description
		'LOC_CIVILIZATION_CVS_BERBER_ADJECTIVE', -- Adjective
		'CIVILIZATION_LEVEL_FULL_CIV', -- StartingCivilizationType
		22, -- RandomCityNameDepth
		'ETHNICITY_MEDIT' -- Ethnicity
		);	
-----------------------------------------------			
-- CityNames			
-----------------------------------------------		
INSERT INTO CityNames	
		(CivilizationType,			CityName)	
VALUES	('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TLEMCEN'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_FEZ'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TOUGGOURT'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_GHARDAIA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_CONSTANTINE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_BEJAIA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TETOUAN'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ANNABA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_BISKRA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_GERMA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_CHERCHELL'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_OUARZAZATE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_GHADAMES'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_SETIF'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MISURATA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_SALE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TAMANRASSET'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_LAGHOUAT'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_AGADEZ'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ESSOUK'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_AGADIR'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TINMEL'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_BATNA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TEBESSA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_DJERBA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_KHENCHELA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MARRAKESH'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ALGIERS'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TUNIS'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_TRIPOLI'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TIZI_OUZOU'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_KAIROUAN'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_OUARGLA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_ORAN'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_SIJILMASA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_BLIDA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_AIT_BENHADDOU'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TATAOUINE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ZUWARAH'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TENES'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MEDEA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_GHAT'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TIARET'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_UBARI'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MEKNES'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TIMGAD'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_GAFSA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_LARACHE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ABALESSA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_OUJDA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ALTAVA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MOGADOR'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_FIGUIG'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MASCARA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_DJANET'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TOZEUR'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_JIJEL'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_ARAOUANE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_THAGASTE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TAMENTIT'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_CEUTA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_MELILLA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TANGIER'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_CASABLANCA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_TAGHAZA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_AUZIA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_DOUIRET'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_CHENINI'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_SAFI'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_LAMBAESIS'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_SIGA'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_THELEPTE'),
		('CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_SC_RAS_KEBDANA');
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------	
INSERT INTO CivilizationCitizenNames	
		(CivilizationType,			CitizenName,									Female,		Modern)
VALUES	('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_1',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_2',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_3',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_4',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_5',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_6',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_7',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_8',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_9',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MALE_10',				0,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_1',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_2',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_3',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_4',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_5',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_6',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_7',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_8',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_9',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_FEMALE_10',				1,			0),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_1',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_2',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_3',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_4',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_5',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_6',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_7',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_8',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_9',			0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_MALE_10',		0,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_1',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_2',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_3',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_4',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_5',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_6',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_7',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_8',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_9',		1,			1),
		('CIVILIZATION_CVS_BERBER',	'LOC_CITIZEN_CVS_BERBER_MODERN_FEMALE_10',		1,			1);	
-----------------------------------------------			
-- CivilizationInfo			
-----------------------------------------------		
INSERT INTO CivilizationInfo	
		(CivilizationType,			Header,						Caption,								SortIndex)	
VALUES	('CIVILIZATION_CVS_BERBER',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_CVS_BERBER_LOCATION',		10),	
		('CIVILIZATION_CVS_BERBER',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_CVS_BERBER_SIZE',			20),	
		('CIVILIZATION_CVS_BERBER',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_CVS_BERBER_POPULATION',	30),	
		('CIVILIZATION_CVS_BERBER',	'LOC_CIVINFO_CAPITAL', 		'LOC_CIVINFO_CVS_BERBER_CAPITAL',		40);
-----------------------------------------------			
-- StartBias
-----------------------------------------------	
INSERT INTO StartBiasFeatures
		(CivilizationType,					FeatureType,			Tier)
VALUES	('CIVILIZATION_CVS_BERBER',			'FEATURE_OASIS',		1);

INSERT INTO StartBiasTerrains
		(CivilizationType,					TerrainType,				Tier)
VALUES	('CIVILIZATION_CVS_BERBER',			'TERRAIN_DESERT',			1),
		('CIVILIZATION_CVS_BERBER',			'TERRAIN_DESERT_MOUNTAIN',	3),
		('CIVILIZATION_CVS_BERBER',			'TERRAIN_DESERT_HILLS',		2);
