-- CVS_BerberCS_Sale
-- Author: thecrazyscotsman
-- DateCreated: 12/18/2017 6:01:21 PM
--------------------------------------------------------------
--=====
--TYPES
--=====
INSERT INTO Types (Type, Kind)
	VALUES
		('CVS_CIVILIZATION_SALE', 'KIND_CIVILIZATION'),
		('CVS_LEADER_MINOR_CIV_SALE', 'KIND_LEADER'),
		('CVS_MINOR_CIV_SALE_TRAIT', 'KIND_TRAIT'),
		('CVS_MODIFIER_SALE_NAVAL_RAIDER_EXTRA_ATTACK', 'KIND_MODIFIER'),
		('CVS_MODIFIER_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE', 'KIND_MODIFIER');

--===============
--TYPE PROPERTIES
--===============
INSERT INTO TypeProperties (Type, Name, Value)
	VALUES
		('CVS_CIVILIZATION_SALE', 'CityStateCategory', 'MILITARISTIC');

--=============
--CIVILIZATIONS
--=============
INSERT INTO Civilizations (CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity)
	VALUES
		('CVS_CIVILIZATION_SALE', 'LOC_CVS_CIVILIZATION_SALE_NAME', 'LOC_CVS_CIVILIZATION_SALE_DESCRIPTION', 'LOC_CVS_CIVILIZATION_SALE_ADJECTIVE', 'CIVILIZATION_LEVEL_CITY_STATE', 1, 'ETHNICITY_MEDIT'); 

--=======
--LEADERS
--=======
INSERT INTO CivilizationLeaders (CivilizationType, LeaderType, CapitalName)
	VALUES
		('CVS_CIVILIZATION_SALE', 'CVS_LEADER_MINOR_CIV_SALE', 'LOC_CVS_CITY_NAME_SALE');

INSERT INTO Leaders (LeaderType, Name, InheritFrom)
	VALUES
		('CVS_LEADER_MINOR_CIV_SALE', 'LOC_CVS_CIVILIZATION_SALE_NAME', 'LEADER_MINOR_CIV_MILITARISTIC');

--======
--TRAITS
--======
INSERT INTO LeaderTraits (LeaderType, TraitType)
	VALUES
		('CVS_LEADER_MINOR_CIV_SALE', 'CVS_MINOR_CIV_SALE_TRAIT');

INSERT INTO Traits (TraitType, Name, Description)
	VALUES
		('CVS_MINOR_CIV_SALE_TRAIT', 'LOC_CVS_LEADER_TRAIT_SALE_NAME', 'LOC_CVS_LEADER_TRAIT_SALE_DESCRIPTION');

INSERT INTO TraitModifiers (TraitType, ModifierId)
	VALUES
		('CVS_MINOR_CIV_SALE_TRAIT', 'CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_EXTRA_ATTACK'),
		('CVS_MINOR_CIV_SALE_TRAIT', 'CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_ATTACK_AND_MOVE');

--=================
--DYNAMIC MODIFIERS
--=================
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
	VALUES
		('CVS_MODIFIER_SALE_NAVAL_RAIDER_EXTRA_ATTACK', 'COLLECTION_PLAYER_UNITS', 'EFFECT_ADJUST_UNIT_NUM_ATTACKS'),
		('CVS_MODIFIER_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE', 'COLLECTION_PLAYER_UNITS', 'EFFECT_ADJUST_UNIT_ATTACK_AND_MOVE');

--=========
--MODIFIERS
--=========
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId)	
	VALUES
		('CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_EXTRA_ATTACK', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', NULL, 'PLAYER_IS_SUZERAIN'),
		('CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_ATTACK_AND_MOVE', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', NULL, 'PLAYER_IS_SUZERAIN'),
		('CVS_MINOR_CIV_SALE_NAVAL_RAIDER_EXTRA_ATTACK', 'CVS_MODIFIER_SALE_NAVAL_RAIDER_EXTRA_ATTACK', NULL, 'CVS_BERBER_REQUIREMENTSET_UNIT_IS_NAVAL_RAIDER'),
		('CVS_MINOR_CIV_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE', 'CVS_MODIFIER_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE', NULL, 'CVS_BERBER_REQUIREMENTSET_UNIT_IS_NAVAL_RAIDER');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES
		('CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_EXTRA_ATTACK', 'ModifierId', 'CVS_MINOR_CIV_SALE_NAVAL_RAIDER_EXTRA_ATTACK'),
		('CVS_MINOR_CIV_SALE_UNIQUE_INFLUENCE_BONUS_ATTACK_AND_MOVE', 'ModifierId', 'CVS_MINOR_CIV_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE'),
		('CVS_MINOR_CIV_SALE_NAVAL_RAIDER_EXTRA_ATTACK', 'Amount', 1),
		('CVS_MINOR_CIV_SALE_NAVAL_RAIDER_ATTACK_AND_MOVE', 'CanMove', 'true');

--=============
--REQUIREMENTS
--=============
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
	VALUES
		('CVS_BERBER_REQUIREMENTSET_UNIT_IS_NAVAL_RAIDER', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES
		('CVS_BERBER_REQUIREMENTSET_UNIT_IS_NAVAL_RAIDER', 'CVS_BERBER_REQUIRES_CLASS_NAVAL_RAIDER');
		
INSERT INTO Requirements (RequirementId, RequirementType)
	VALUES
		('CVS_BERBER_REQUIRES_CLASS_NAVAL_RAIDER', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
	VALUES
		('CVS_BERBER_REQUIRES_CLASS_NAVAL_RAIDER', 'UnitPromotionClass', 'PROMOTION_CLASS_NAVAL_RAIDER');

--==========
--CITY NAMES
--==========		
INSERT INTO CityNames (CivilizationType, CityName)
	VALUES
		('CVS_CIVILIZATION_SALE', 'LOC_CVS_CITY_NAME_SALE');

--=============
--PLAYER COLORS
--=============
INSERT INTO PlayerColors (Type, Usage, PrimaryColor, SecondaryColor, TextColor)
	VALUES
		('CVS_CIVILIZATION_SALE', 'Minor', 'COLOR_PLAYER_CITY_STATE_PRIMARY', 'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY', 'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY');

--============
--START BIASES
--============
INSERT INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
	VALUES
		('CVS_CIVILIZATION_SALE', 'TERRAIN_COAST', 1);